### ISSUE TITLE
ubuntu20.04 noetic  no element "gconfaudiosrc"  error

### ISSUE THREAD

**Issue by iamzhuang** [mikeferguson/pocketsphinx#26]
hello, 
  I run the newst branch src in ros noetic with the cmd :roslaunch pocketsphinx turtlebot_voice_cmd.launch 
and it had the error below:

... logging to /home/kolli/.ros/log/7838f526-ff2d-11eb-930a-f143778bbbbd/roslaunch-kolli-4488.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://kolli:38345/

SUMMARY
========

PARAMETERS
 * /recognizer/dict: /home/kolli/kolli...
 * /recognizer/lm: /home/kolli/kolli...
 * /rosdistro: noetic
 * /rosversion: 1.15.11

NODES
  /
    recognizer (pocketsphinx/recognizer.py)
    voice_cmd_vel (pocketsphinx/voice_cmd_vel.py)

auto-starting new master
process[master]: started with pid [4496]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7838f526-ff2d-11eb-930a-f143778bbbbd
process[rosout-1]: started with pid [4506]
started core service [/rosout]
process[recognizer-2]: started with pid [4509]
process[voice_cmd_vel-3]: started with pid [4514]
Traceback (most recent call last):
  File "/home/kolli/kolli-01/src/pocketsphinx/nodes/recognizer.py", line 171, in <module>
    start = recognizer()
  File "/home/kolli/kolli-01/src/pocketsphinx/nodes/recognizer.py", line 79, in __init__
    self.start_recognizer()
  File "/home/kolli/kolli-01/src/pocketsphinx/nodes/recognizer.py", line 86, in start_recognizer
    self.pipeline = gst.parse_launch(self.launch_config)
gi.repository.GLib.Error: gst_parse_error: no element "gconfaudiosrc" (1)

(python3:4509): Gtk-CRITICAL **: 15:33:53.862: gtk_main_quit: assertion 'main_loops != NULL' failed

I had install the following:
sudo apt-get install gstreamer1.0-pocketsphinx

is the gst1.0 had not the element "gconfaudiosrc"?  I can't find the element on the gst1.0..   How can I do ?

**Comment by iamzhuang** [comment]
sorry ,I had not read the src ....   I had not set the mic name!!  so set it , then solved
